rm(list=ls())

xgrid<-seq(-3.5,3.5,0.01)
ygrid<--xgrid^4

pdf('climb1.pdf')
plot(xgrid,ygrid,xlim=c(-3,3),ylim=c(-100,4),lwd=4,"l",xlab='x',ylab='f(x)',main='Step Size x=2')
lines(c(-1.5,-3),c(0,-48),col='magenta',lty=2,lwd=3)
text(-2,-16,'Step Size = 2/3',col='magenta',pos=4)
dev.off()
pdf('climb2.pdf')
plot(xgrid,ygrid,xlim=c(-3,3),ylim=c(-100,4),lwd=4,"l",xlab='x',ylab='f(x)',main='Step Size x=-1')
lines(c(1,-3),c(7,-9),col='red',lty=2,lwd=3)
text(-1.5,-1,'Step Size = 1/3',col='red',pos=1)
dev.off()
pdf('climb3.pdf')
plot(xgrid,ygrid,xlim=c(-3,3),ylim=c(-100,4),lwd=4,"l",xlab='x',ylab='f(x)',main='Step Size x=1')
lines(c(-1,3),c(7,-9),col='blue',lty=2,lwd=3)
text(1,-1,'Step Size = -1/3',col='blue',pos=4)
dev.off()

pdf('climb4.pdf')
plot(xgrid,ygrid,xlim=c(-3,3),ylim=c(-100,10),lwd=4,"l",xlab='x',ylab='f(x)',main='Second Derivative')
lines(xgrid,-8*xgrid^4,lwd=4,col='red')
text(0,0,expression(paste("f''(x)=-12",x^2)),pos=3)
text(0,0,expression(paste("f''(x)=-96",x^2)),pos=1,col='red')
dev.off()
